import type { Metadata } from 'next';
import './globals.css';
import { Roboto } from 'next/font/google';
import type { ReactElement } from 'react';

import Header from '@/components/Header/Header';
import { getUserFromCookie } from '@/utils/getUserFromCookie';

import Providers from './providers';

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next-firebase',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<ReactElement> {
  const user = await getUserFromCookie();
  return (
    <html lang="en">
      <body className={`${roboto.className} m-auto flex min-h-screen max-w-5xl flex-col pt-20 antialiased`}>
        <Providers user={user}>
          <Header />
          <main className="flex flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
